In [75]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
import cv2

In [65]:
!tar -xvf /content/disease-classification_1.tar.gz

./
./.DS_Store
./._.DS_Store
./variables/
./variables/variables.data-00000-of-00001
./variables/._variables.data-00000-of-00001
./variables/variables.index
./variables/._variables.index
./._variables
./saved_model.pb
./._saved_model.pb
./assets/
./._assets


In [66]:
!ls /content

assets			      disease-classification_1.tar.gz  saved_model.pb
disease-classification_1.tar  sample_data		       variables


In [67]:
!ls /content/extracted_directory_name


ls: cannot access '/content/extracted_directory_name': No such file or directory


In [115]:
model = tf.saved_model.load('/content')

In [109]:
model = tf.saved_model.load('/content')
signatures = list(model.signatures.keys())
print(signatures)

['serving_default']


In [116]:
plt.imshow(cv2.cvtColor(e_f[0], cv2.COLOR_BGR2RGB))

error: ignored

In [119]:
e_f[0]/255.0

array([[[3.07574010e-03, 3.19876970e-03, 2.98346790e-03],
        [3.13725490e-03, 3.24490581e-03, 3.13725490e-03],
        [3.29104191e-03, 3.36793541e-03, 3.26028451e-03],
        ...,
        [1.44559785e-03, 2.02998847e-03, 7.22798923e-04],
        [1.43021915e-03, 1.99923106e-03, 3.69088812e-04],
        [1.49173395e-03, 2.10688197e-03, 4.61361015e-05]],

       [[3.09111880e-03, 3.13725490e-03, 2.92195309e-03],
        [3.16801230e-03, 3.19876970e-03, 3.01422530e-03],
        [3.22952710e-03, 3.26028451e-03, 3.06036140e-03],
        ...,
        [1.41484045e-03, 1.96847366e-03, 8.76585928e-04],
        [1.44559785e-03, 1.99923106e-03, 5.99769319e-04],
        [1.49173395e-03, 2.10688197e-03, 1.69165705e-04]],

       [[3.19876970e-03, 3.16801230e-03, 2.92195309e-03],
        [3.22952710e-03, 3.21414840e-03, 2.93733180e-03],
        [3.24490581e-03, 3.26028451e-03, 3.01422530e-03],
        ...,
        [1.35332564e-03, 1.87620146e-03, 9.38100730e-04],
        [1.38408304e-03, 1.95

In [120]:
pn = ['Tomato Healthy', 'Tomato Septoria Leaf Spot', 'Tomato Bacterial Spot', 'Tomato Blight', 'Cabbage Healthy', 'Tomato Spider Mite', 'Tomato Leaf Mold', 'Tomato_Yellow Leaf Curl Virus', 'Soy_Frogeye_Leaf_Spot', 'Soy_Downy_Mildew', 'Maize_Ravi_Corn_Rust', 'Maize_Healthy', 'Maize_Grey_Leaf_Spot', 'Maize_Lethal_Necrosis', 'Soy_Healthy', 'Cabbage Black Rot']

In [133]:
e = cv2.imread(r"/content/maize.png")
e_r = cv2.cvtColor(cv2.resize(e, (300, 300)), cv2.COLOR_BGR2RGB)/255.0
e_f = np.expand_dims(e_r, axis=0)
print(e_f.shape)
infer = model.signatures['serving_default']

# Assuming 'input_data' is your prepared input data tensor
tensor = tf.convert_to_tensor(e_f)
float_tensor = tf.cast(tensor, dtype=tf.float32)
output_data = infer(float_tensor)

pn[np.argmax(output_data["dense_1"][0])]

(1, 300, 300, 3)


'Maize_Healthy'

In [132]:
output_data["dense_1"][0]

<tf.Tensor: shape=(16,), dtype=float32, numpy=
array([0.17216952, 0.02294196, 0.02271692, 0.018627  , 0.0102324 ,
       0.01028759, 0.12588784, 0.00691381, 0.00624391, 0.00205372,
       0.04402184, 0.5124458 , 0.00828663, 0.02219902, 0.00194593,
       0.01302609], dtype=float32)>

In [134]:
output_data

{'dense_1': <tf.Tensor: shape=(1, 16), dtype=float32, numpy=
 array([[0.17216952, 0.02294196, 0.02271692, 0.018627  , 0.0102324 ,
         0.01028759, 0.12588784, 0.00691381, 0.00624391, 0.00205372,
         0.04402184, 0.5124458 , 0.00828663, 0.02219902, 0.00194593,
         0.01302609]], dtype=float32)>}

In [135]:
def load_model(model_path: str):
  model = tf.saved_model.load('/content')
  signatures = list(model.signatures.keys())
  return model, signatures

In [136]:

  pn = ['Tomato Healthy', 'Tomato Septoria Leaf Spot', 'Tomato Bacterial Spot', 'Tomato Blight', 'Cabbage Healthy', 'Tomato Spider Mite', 'Tomato Leaf Mold', 'Tomato_Yellow Leaf Curl Virus', 'Soy_Frogeye_Leaf_Spot', 'Soy_Downy_Mildew', 'Maize_Ravi_Corn_Rust', 'Maize_Healthy', 'Maize_Grey_Leaf_Spot', 'Maize_Lethal_Necrosis', 'Soy_Healthy', 'Cabbage Black Rot']

  e = cv2.imread(r"/content/maize.png")
  e_r = cv2.cvtColor(cv2.resize(e, (300, 300)), cv2.COLOR_BGR2RGB)/255.0
  e_f = np.expand_dims(e_r, axis=0)
  print(e_f.shape)
  infer = model.signatures['serving_default']

  # Assuming 'input_data' is your prepared input data tensor
  tensor = tf.convert_to_tensor(e_f)
  float_tensor = tf.cast(tensor, dtype=tf.float32)
  output_data = infer(float_tensor)

  pn[np.argmax(output_data["dense_1"][0])]


(1, 300, 300, 3)


'Maize_Healthy'

In [143]:
# the function for the maize prediction
def image_pred(file_path: str, model):

  plant_names = ['Tomato Healthy', 'Tomato Septoria Leaf Spot', 'Tomato Bacterial Spot', 'Tomato Blight', 'Cabbage Healthy', 'Tomato Spider Mite', 'Tomato Leaf Mold', 'Tomato_Yellow Leaf Curl Virus', 'Soy_Frogeye_Leaf_Spot', 'Soy_Downy_Mildew', 'Maize_Ravi_Corn_Rust', 'Maize_Healthy', 'Maize_Grey_Leaf_Spot', 'Maize_Lethal_Necrosis', 'Soy_Healthy', 'Cabbage Black Rot']
# e = image_name
  image_name = cv2.imread(r"/content/maize.png")
# e_r = resized image + rgb image
  e_r = cv2.cvtColor(cv2.resize(e, (300, 300)), cv2.COLOR_BGR2RGB)/255.0
# e_f = expanded_image
  e_f = np.expand_dims(e_r, axis=0)
  print(e_f.shape)


  # Assuming 'input_data' is your prepared input data tensor
  tensor = tf.convert_to_tensor(e_f)
  float_tensor = tf.cast(tensor, dtype=tf.float32)

  infer = model.signatures['serving_default']
  output_data = infer(float_tensor)

  predicted_health = pn[np.argmax(output_data["dense_1"][0])]
  return predicted_health, max(output_data["dense_1"][0])


In [144]:
image_pred('/content/colored corn.webp', model)

(1, 300, 300, 3)


('Maize_Healthy', <tf.Tensor: shape=(), dtype=float32, numpy=0.5124458>)

In [ ]:
# input is going to be file path and the output is going to be maize healthy